"""Initial migration

Revision ID: c8fca78d5622
Revises: 13b3c2e04cf3  # Update this with the actual previous migration ID
Create Date: 2024-12-24 14:12:26.951022
"""

from alembic import op
import sqlalchemy as sa

# Revision identifiers, used by Alembic.
revision = 'c8fca78d5622'
# Replace with the actual ID of the last migration in your project
down_revision = '13b3c2e04cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'UserFeedback',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user', sa.String(), nullable=False),
        sa.Column('feedback', sa.Text(), nullable=False),
        sa.Column('status', sa.Boolean(), nullable=False, default=False),
        sa.ForeignKeyConstraint(
            ['user'], ['user.username'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserFeedback')
    # ### end Alembic commands ###
